// 公共
def repository_url = "swr.cn-north-4.myhuaweicloud.com"
def region_name = "cn-north-4"
def image_dir = "sunshine-technology"

// 项目
def app_name = "demo-app"
def git_repo = "https://github.com/findyou230/jar-k8s-demo.git"
def git_branch = "master"
def mvn_dir = "/opt/maven"
def mvn_cmd = "mvn clean package -Pproduct -Dmaven.test.skip=true"
def base_image = "swr.cn-north-4.myhuaweicloud.com/sunshine-technology/openjdk:8u181-jdk"
def jar_name = "hello-0.0.1-SNAPSHOT.jar"
def rep_num = "2"
def namespace_name = "webapp"
def secret_name = "default-secret"

// 认证
def gitlab_auth = "gitlab-user-admin"
def github_auth = "github-email-id"
def k8s_auth = "k8s-test-kube-config"    //存储在 Jenkins 凭证存储中的 kubeconfig 的凭证 ID

pipeline{
	agent{
		kubernetes{
			cloud "cluster-test"
			label "jenkins-agent"
        }
	}
	stages{
		stage("Check info"){
			steps{
				script{
 				    echo "1. First, let's test the first step"
 				    echo "先查看下pod的IP"
 				    sh "ip a"
 				    echo "查看下java的版本"
 				    sh "java -version"
 				    echo "查看docker版本"
 				    sh "docker -v"
				}
			}
		}
		stage('Pull program'){
			steps{      //包含一个或多个在stage块中执行的step序列
				echo "2. To start, pull the Git project"
				git branch: "${git_branch}", credentialsId: "${github_auth}", url: "${git_repo}"
				//checkout scm  
				script { 
 					build_tag = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
				//	if (env.BRANCH_NAME != 'master' && env.BRANCH_NAME != null) {
				//	build_tag = "${env.BRANCH_NAME}-${build_tag}"
				//  }					
			    } 
				echo "Build Tag ${build_tag}"
				sh "pwd && ls"
			}
		}
		stage("Compile"){
			steps{
				echo "3. Compiling with Maven"
				//sh "mvn -v"
				//sh "${mvn_cmd}"
				sh "pwd && ls && rm -rf project_dir"
				sh "mkdir ./project_dir && cp ${jar_name} ./project_dir/"
				sh "ls ./project_dir/"
			}
		}
		stage("Check pod"){
 	        	steps{
				echo "4. Check the POD and kubectl command before building"
				sh "kubectl get nodes"
				sh "kubectl get pod -n jenkins"
				//sh "ping swr.cn-north-4.myhuaweicloud.com -c 3"
 	        	}
		}
		stage("Build image"){
			steps{      //如果源路径是个目录,如果目标路径是个已经存在的目录,则docker会把源路径目录下的文件拷贝到该目录下。
				echo "5. build docker images and push to Repositories"
				sh "pwd"
				sh "cd project_dir  && pwd"
				sh "pwd"
				sh "mv Dockerfile ./project_dir/ && ls && cd project_dir && ls -l"
				//使用jenkins中secret text类型的credentials的特定方法
			withCredentials([string(credentialsId: 'jenkins-access-key-id', variable: 'ACCESS_KEY_ID'),
				string(credentialsId: 'jenkins-secret-access-key', variable: 'SECRET_ACCESS_KEY')]) {
				//节点执行docker login命令进行认证
				sh "docker login -u ${region_name}@${ACCESS_KEY_ID} -p ${SECRET_ACCESS_KEY} ${repository_url}"
                //构建镜像
				sh "cd project_dir && docker build -t ${repository_url}/${image_dir}/${app_name}:${git_branch}_${build_tag} ."
				//推送镜像到华为云镜像仓库				
				sh "docker push ${repository_url}/${image_dir}/${app_name}:${git_branch}_${build_tag}"
				}
			}
		}
		stage("Deploy"){
			steps{
				script{
					try {
						echo "6. Deploy the service to the Kubernetes cluster"
						echo "${namespace_name}"
						//sh "rm -rf /opt/k8s/yaml/deploy.yaml"
						//sh "cp /opt/k8s/deploy-template.yaml /opt/k8s/yaml/deploy.yaml"
						sh "cat ./deploy/deploy.yaml"
						script{
							sh "sed -i 's#\$NAMESPACE_NAME#${namespace_name}#g' ./deploy/deploy.yaml"
							sh "sed -i 's#\${IMAGE_URL}#${repository_url}/${image_dir}/${app_name}:${git_branch}_${build_tag}#g' ./deploy/deploy.yaml"
							sh "sed -i 's#\${SECRET_NAME}#${secret_name}#g' ./deploy/deploy.yaml"
							sh "sed -i 's#\${APP_NAME}#${app_name}#g' ./deploy/deploy.yaml"
							sh "sed -i 's#\${REP_NUM}#${rep_num}#g' ./deploy/deploy.yaml"
						}
						sh "cat ./deploy/deploy.yaml"						
						sh "kubectl apply -f ./deploy/deploy.yaml --record"
						sh "sleep 10 && kubectl get pod -n webapp"
						println "hooray, success"
					}
					catch (exc) {  //如果try执行失败，则执行catch部分
						println "oh no! Deployment failed! "
						println exc
					}
				}
			}
		}
		stage("Finally"){
			steps{
				echo "构建，部署完成，请检查日志，确认没有报错信息，服务启动是否正常"
			}
		}
	}
}
