apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE_NAME}
  labels:
    app: ${APP_NAME}
    version: v1
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: ${SVC_PORT}
      targetPort: ${CONTAINER_PORT}
  selector:
    app: ${APP_NAME}
    version: v1
  type: ClusterIP
  sessionAffinity: None
